stages:
  - primary_stage

image: node:6.11.2

variables:
  GLOBAL_VAR: "this GLOBAL_VAR should mostly always be set."

.use-local-inheritence:
  variables:
    AN_INHERITED_VARIABLE: "inheritence of local vars works"

print_hello:
  stage: primary_stage
  before_script:
    - echo Some setup here
  cache:
    untracked: true
  only:
    - master
  script:
    - echo hello

print_goodbye:
  stage: primary_stage
  cache:
    untracked: true
    policy: pull
  only:
    - master
  variables:
    GOODBYE: "tara"
  script:
    - echo $GOODBYE a bit
    - echo $GLOBAL_VAR is set?

yaml_merge: &yaml_merge
  variables:
    MERGED: "Oh yeah, we merged alright via yaml."
  script: echo Tada

tired_starlings:
  <<: *yaml_merge
  extends: .use-local-inheritence
  script:
    - echo Does local inheritance work? $AN_INHERITED_VARIABLE
